### ISSUE TITLE
Add ability to specify 'known' imports from a YAML/JSON config file

### ISSUE THREAD

**Issue by akashb95** [akashb95/pyllemi#8]
Depends on #3 and #7. Could be a (decent) workaround for #1 when imports are dynamic. 

Allow a JSON/YAML config file (e.g. .pyllemi.json), which can set known imports for certain targets. E.g:
```yaml
known_imports:
  - src: //path/to:target
    deps:
       - //path/to:dep
       - //path/to/another:dep
```

These dependency targets will then be injected into the src targets.
